#define NUMBER_OF_DAYS 6
#define MAX_HOURS_PER_DAY 5

// Hard constraint specfications
#define HARD_CAPACITY_CONSTRAINT
#define HARD_VENUE_CONFLICT
#define HARD_VENUE_TYPE
#define HARD_MAX_SESSIONS
#define HARD_PARTY_DUPLICATE
#define HARD_SUFFECIENT_TIMESLOT
#define SOFT_STUDENT_TRAVELTIME
#define MAXIMIZE_CHUNKING
