#define NUMBER_OF_DAYS 6
#define MAX_HOURS_PER_DAY 5

// Hard constraint specfications
#define HARD_CAPACITY_CONSTRAINT
#define HARD_VENUE_CONFLICT
#define HARD_VENUE_TYPE
#define HARD_MAX_SESSIONS
#define HARD_PARTY_DUPLICATE
#define HARD_SUFFECIENT_TIMESLOT
#define SOFT_STUDENT_TRAVELTIME
#define SOFT_MAXIMIZE_CHUNKING
#define SOFT_ROOM_UTILIZATION
#define SOFT_AVOID_EARLYLATE_TIME
#define SOFT_ROOM_CAPACITY_UTILIZATION
#define SOFT_COMMON_TIMSLOT_EMPTY
#define SOFT_MINIMIZE_BACKTOBACK_TEACHERCLASSES
